// src/App.vue
<template>
  <div id="app">
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <router-link class="navbar-brand" to="/">
          <i class="fas fa-user-tie me-2"></i>Erik Stuble
        </router-link>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarNav"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ms-auto">
            <li class="nav-item">
              <router-link
                class="nav-link"
                to="/"
                :class="{ active: $route.path === '/' }"
              >
                <i class="fas fa-home me-1"></i>Home
              </router-link>
            </li>
            <li class="nav-item">
              <router-link
                class="nav-link"
                to="/about"
                :class="{ active: $route.path === '/about' }"
              >
                <i class="fas fa-user me-1"></i>About
              </router-link>
            </li>
            <li class="nav-item dropdown">
              <a
                class="nav-link dropdown-toggle"
                href="#"
                role="button"
                data-bs-toggle="dropdown"
              >
                <i class="fas fa-briefcase me-1"></i>Experience
              </a>
              <ul class="dropdown-menu">
                <li v-for="experience in experiences" :key="experience.id">
                  <router-link
                    class="dropdown-item"
                    :to="`/experience/${experience.id}`"
                  >
                    {{ experience.company }}
                  </router-link>
                </li>
              </ul>
            </li>
            <li class="nav-item">
              <router-link
                class="nav-link"
                to="/skills"
                :class="{ active: $route.path === '/skills' }"
              >
                <i class="fas fa-code me-1"></i>Skills
              </router-link>
            </li>
            <li class="nav-item">
              <router-link
                class="nav-link"
                to="/contact"
                :class="{ active: $route.path === '/contact' }"
              >
                <i class="fas fa-envelope me-1"></i>Contact
              </router-link>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <!-- Main Content -->
    <main class="main-content">
      <router-view />
    </main>

    <!-- Footer -->
    <footer class="bg-dark text-white text-center py-4 mt-5">
      <div class="container">
        <p class="mb-0">
          <i class="fas fa-copyright me-2"></i>2024 Erik Stuble. All rights
          reserved.
        </p>
      </div>
    </footer>
  </div>
</template>

<script setup lang="ts">
import { useResumeStore } from "@/stores/resume";

// Use the store to get data
const { experiences } = useResumeStore();
</script>

<style scoped>
.main-content {
  padding-top: 76px;
}
</style>

// frontend/src/App.tsx
import React from 'react';
import { BrowserRouter as Router, Routes, Route, Link, useLocation } from 'react-router-dom';
import { useResumeStore } from './stores/resumeStore';
import HomeView from './views/HomeView';
import AboutView from './views/AboutView';
import ExperienceView from './views/ExperienceView';
import ExperienceDetailView from './views/ExperienceDetailView';
import SkillsView from './views/SkillsView';
import ContactView from './views/ContactView';

// Import Bootstrap CSS and JS
import 'bootstrap/dist/css/bootstrap.min.css';
import 'bootstrap/dist/js/bootstrap.bundle.min.js';
import '@fortawesome/fontawesome-free/css/all.min.css';

// Import custom styles
import './assets/main.css';

// Environment banner component
const EnvironmentBanner: React.FC = () => {
  const env = process.env.NODE_ENV || 'development';
  const showEnvBanner = env !== 'production';
  
  if (!showEnvBanner) return null;

  const envLabel = env === 'development' 
    ? 'Development Environment' 
    : env === 'test'
      ? 'Test Environment'
      : env;
  
  const envClass = env === 'development' ? 'env-banner-dev' : 'env-banner-test';

  return (
    <div className={`env-banner ${envClass}`}>
      {envLabel}
    </div>
  );
};

// Navigation component
const Navigation: React.FC = () => {
  const location = useLocation();

  const closeNavbar = () => {
    const navbarCollapse = document.getElementById('navbarNav');
    if (navbarCollapse && navbarCollapse.classList.contains('show')) {
      // Bootstrap 5 uses Collapse instance
      const collapse = (window as any).bootstrap && (window as any).bootstrap.Collapse
        ? (window as any).bootstrap.Collapse.getOrCreateInstance(navbarCollapse)
        : null;
      if (collapse) {
        collapse.hide();
      } else {
        // fallback: remove 'show' class
        navbarCollapse.classList.remove('show');
      }
    }
  };

  return (
    <nav className="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div className="container">
        <Link className="navbar-brand" to="/">
          <i className="fas fa-user-tie me-2"></i>Erik Stuble
        </Link>
        <button
          className="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarNav"
        >
          <span className="navbar-toggler-icon"></span>
        </button>
        <div className="collapse navbar-collapse" id="navbarNav">
          <ul className="navbar-nav ms-auto">
            <li className="nav-item">
              <Link
                className={`nav-link ${location.pathname === '/' ? 'active' : ''}`}
                to="/"
                onClick={closeNavbar}
              >
                <i className="fas fa-home me-1"></i>Home
              </Link>
            </li>
            <li className="nav-item">
              <Link
                className={`nav-link ${location.pathname === '/about' ? 'active' : ''}`}
                to="/about"
                onClick={closeNavbar}
              >
                <i className="fas fa-user me-1"></i>About
              </Link>
            </li>
            <li className="nav-item">
              <Link
                className={`nav-link ${location.pathname.startsWith('/experience') ? 'active' : ''}`}
                to="/experience"
                onClick={closeNavbar}
              >
                <i className="fas fa-briefcase me-1"></i>Experience
              </Link>
            </li>
            <li className="nav-item">
              <Link
                className={`nav-link ${location.pathname === '/skills' ? 'active' : ''}`}
                to="/skills"
                onClick={closeNavbar}
              >
                <i className="fas fa-code me-1"></i>Skills
              </Link>
            </li>
            <li className="nav-item">
              <Link
                className={`nav-link ${location.pathname === '/contact' ? 'active' : ''}`}
                to="/contact"
                onClick={closeNavbar}
              >
                <i className="fas fa-envelope me-1"></i>Contact
              </Link>
            </li>
          </ul>
        </div>
      </div>
    </nav>
  );
};

// Footer component
const Footer: React.FC = () => {
  return (
    <footer className="bg-dark text-white text-center py-4 mt-5">
      <div className="container">
        <p className="mb-0">
          <i className="fas fa-copyright me-2"></i>2024 Erik Stuble. All rights
          reserved.
        </p>
      </div>
    </footer>
  );
};

function App() {
  return (
    <Router>
      <div id="app">
        <EnvironmentBanner />
        <Navigation />
        
        {/* Main Content */}
        <main className="main-content">
          <Routes>
            <Route path="/" element={<HomeView />} />
            <Route path="/about" element={<AboutView />} />
            <Route path="/experience" element={<ExperienceView />} />
            <Route path="/experience/:slug" element={<ExperienceDetailView />} />
            <Route path="/skills" element={<SkillsView />} />
            <Route path="/contact" element={<ContactView />} />
          </Routes>
        </main>

        <Footer />
      </div>
    </Router>
  );
}

export default App;
